- name: Setup ACR and images
  hosts: localhost
  tags: acr
  gather_facts: false
  vars_files:
    - secrets/credentials.yml
  tasks:
    - name: Pull, tag and push image to ACR
      include_role:
        name: acr

- name: Setup webserver
  hosts: webapp
  tags: vm
  gather_facts: false
  vars_files:
    - secrets/credentials.yml
  tasks:
    - name: Configure VM with podman and deploy nginx container
      include_role:
        name: vm

- name: Setup AKS deployment
  hosts: localhost
  tags: aks
  gather_facts: false
  vars_files:
    - secrets/credentials.yml
  tasks:
    - name: Deploy to AKS
      include_role:
        name: aks